### ISSUE TITLE
Issues importing Kismet pcapdump files

### ISSUE THREAD

**Issue by upinarms** [Tylous/SniffAir#17]
When importing a pcapdump file captured using Kismet into offline_capture, I get the following error and SniffAir crashes:

>>  [am_13thfloor]# offline_capture /root/Documents/Kismet_files/Kismet-20171017-12-33-03-1.pcapdump
|[*] Importing /root/Documents//Kismet_files/Kismet-20171017-12-33-03-1.pcapdump
|/---| /
[+] Completed
[+] Cleaning Up Duplicates
Traceback (most recent call last):
  File "SniffAir.py", line 600, in <module>
    main_menu()
  File "SniffAir.py", line 133, in main_menu
    choice()
  File "SniffAir.py", line 113, in choice
    exec_menu(choice)
  File "SniffAir.py", line 151, in exec_menu
    menu_actions[cmd]()
  File "SniffAir.py", line 219, in Workspace
    choice()
  File "SniffAir.py", line 113, in choice
    exec_menu(choice)
  File "SniffAir.py", line 151, in exec_menu
    menu_actions[cmd]()
  File "SniffAir.py", line 390, in Help
    choice()
  File "SniffAir.py", line 113, in choice
    exec_menu(choice)
  File "SniffAir.py", line 151, in exec_menu
    menu_actions[cmd]()
  File "SniffAir.py", line 297, in Offline_Capture
    d.clean_up()
  File "lib/Queries.py", line 51, in clean_up
    qr = dp.read_sql('select * from '+ tb +'', con)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py", line 400, in read_sql
    chunksize=chunksize)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py", line 1453, in read_query
    data = self._fetchall_as_list(cursor)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py", line 1462, in _fetchall_as_list
    result = cur.fetchall()
sqlite3.OperationalError: Could not decode to UTF-8 column 'ESSID' with text '??$?H`l'
root@beast:/opt/SniffAir# 

When I review the am_13thfloor.db file, I find the following entries:
INSERT INTO accessPoints VALUES(NULL,'??$?H`l','18:64:72:58:ff:71','Aruba Networks','52','-64','WPA2','TKIP','PSK');
INSERT INTO accessPoints VALUES('??$?H`l','18:64:72:58:ff:71','Aruba Networks','52',-64,'WPA2','TKIP','PSK');

Testing with a different pcapdump file provides the same results, SniffAir crashes:
>>  [default]# workspace create test
[+]  Workspace test created
 >>  [test]# offline_capture /root/Documents//Kismet_files/Kismet-20171017-12-40-16-1.pcapdump
|[*] Importing /root/Documents/Kismet_files/Kismet-20171017-12-40-16-1.pcapdump
\
[+] Completed
[+] Cleaning Up Duplicates
Traceback (most recent call last):
  File "SniffAir.py", line 687, in <module>
    main_menu()
  File "SniffAir.py", line 137, in main_menu
    choice()
  File "SniffAir.py", line 117, in choice
    exec_menu(choice)
  File "SniffAir.py", line 155, in exec_menu
    menu_actions[cmd]()
  File "SniffAir.py", line 225, in Workspace
    choice()
  File "SniffAir.py", line 117, in choice
    exec_menu(choice)
  File "SniffAir.py", line 155, in exec_menu
    menu_actions[cmd]()
  File "SniffAir.py", line 304, in Offline_Capture
    d.clean_up()
  File "lib/Queries.py", line 51, in clean_up
    qr = dp.read_sql('select * from '+ tb +'', con)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py", line 400, in read_sql
    chunksize=chunksize)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py", line 1453, in read_query
    data = self._fetchall_as_list(cursor)
  File "/usr/local/lib/python2.7/dist-packages/pandas/io/sql.py", line 1462, in _fetchall_as_list
    result = cur.fetchall()
sqlite3.OperationalError: Could not decode to UTF-8 column 'ESSID' with text 'm5'
root@beast:/opt/SniffAir# 

Reviewing the following StackOverflow post and similar ones refer to  "conn.text_factory = str"

https://stackoverflow.com/questions/22751363/sqlite3-operationalerror-could-not-decode-to-utf-8-column

However, I do not see this value defined in SniffAir.py

**Comment by Tylous** [comment]
The error is occurring after the importing process. It looks like the non UTF-8 characters are causing problems with sqlite3. Are both errors related to the same ESSID name or different ones?

**Comment by upinarms** [comment]
The errors occur with different ESSIDs, both of which reside in different pcapdump files from Kismet.

**Comment by Tylous** [comment]
We were able recreate the issue and will have a solution shortly.

**Comment by upinarms** [comment]
Thanks for the hard work!

**Comment by Tylous** [comment]
Issue resolved in latest update.
